sudo: required
services:
  - docker

before_install:
  - docker build -t taxkeller/docker-react -f Dockerfile.dev .

script:
  - docker run taxkeller/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-sample"
  env: "DockerSample-env"
  bucket_name: $AWS_BUCKET_NAME
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

